### ISSUE TITLE
Uncaught Error: input must be buffer, number, or string

### ISSUE THREAD

**Issue by asdfmonster261** [denizkoekden/steamcmd-deno#3]
Sometimes when checking data for a list of appids the following error will be in the logs which causes the api to crash.
```
error: Uncaught Error: input must be buffer, number, or string; received object
    at ensureBuffer (file:///deno-dir/npm/registry.npmjs.org/@doctormckay/stdlib/2.10.0/lib/hashing/crc32.js:90:15)
    at _crc32 (file:///deno-dir/npm/registry.npmjs.org/@doctormckay/stdlib/2.10.0/lib/hashing/crc32.js:94:11)
    at Object.calc [as crc32] (file:///deno-dir/npm/registry.npmjs.org/@doctormckay/stdlib/2.10.0/lib/hashing/crc32.js:105:15)
    at SteamUser.<anonymous> (file:///deno-dir/npm/registry.npmjs.org/steam-user/5.2.0/components/02-connection.js:111:30)
    at file:///deno-dir/npm/registry.npmjs.org/steam-user/5.2.0/components/classes/HandlerManager.js:35:12
    at Array.forEach (<anonymous>)
    at HandlerManager.emit (file:///deno-dir/npm/registry.npmjs.org/steam-user/5.2.0/components/classes/HandlerManager.js:34:12)
    at SteamUser._handleMessage (file:///deno-dir/npm/registry.npmjs.org/steam-user/5.2.0/components/03-messages.js:645:25)
    at SteamUser._handleNetMessage (file:///deno-dir/npm/registry.npmjs.org/steam-user/5.2.0/components/03-messages.js:565:8)
    at TCPConnection._readMessage (file:///deno-dir/npm/registry.npmjs.org/steam-user/5.2.0/components/connection_protocols/tcp.js:232:13)
```
There's no specific appid that this happens with
I am using docker to run the api, but this also happens when running from an executable.

**Comment by denizkoekden** [comment]
Hello,
I will look into this Issue as soon as I have some sparetime. This Project was to learn TypeScript and Deno v2. If you need this urgently you can check out https://github.com/steamcmd/api which is similiar but uses Python and FastAPI.

**Comment by denizkoekden** [comment]
Fixed with latest Release.
